// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lewevnxbrtnzriwocosy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxld2V2bnhicnRuenJpd29jb3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjExMjMsImV4cCI6MjA2MDQzNzEyM30.b9fZPrXHF8d6QLWuRif4DGq5LK2FEtfmrGtfDpO1eRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);